name: Running in two OS
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve the latest code pushed
              uses: actions/checkout@v2

            - name: linux
              run:  echo "Hello,It is in Build Stage"
    
    test:
        runs-on: windows-latest
        needs:   build
        steps:
            - name: Retrieve the latest code pushed
              uses: actions/checkout@v2

            - name: test
              run:  echo "Hello,Testing is done after build"

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Retrieve the latest code pushed
            uses: actions/checkout@v2
          
          - name: deploy
            run:  echo "Hello,deployed"