name: Running Jobs and Storing artifacts
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve the latest code pushed
              uses: actions/checkout@v2

            - name: linux
              run:  |
                echo "Hello,It is in Build Stage"
                echo "Build artifact content" > build_output.txt

            - name: upload artifact
              uses: actions/upload-artifact@v3
              with:
                name: build-artifact
                path: build_output.txt
    
    test:
        runs-on: windows-latest
        needs:   build
        steps:
            - name: Retrieve the latest code pushed
              uses: actions/checkout@v2

            - name: download build artifact
              uses: actions/download-artifact@v3
              with:
                name: build-artifact
                
            - name: test
              run:  |
                 cat build_output.txt
                 echo "Hello,Testing is done after build"

    deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
          - name: Retrieve the latest code pushed
            uses: actions/checkout@v2

          - name: download build artifact
            uses: actions/download-artifact@v3
            with:
                name: build-artifact
          
          - name: deploy
            run:  |
             cat build_output.txt
             echo "Hello,${{secrets.USER_NAME}}"