name: Running in two OS
on: [push]
jobs:
    build_linux:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve the latest code pushed
              uses: actions/checkout@v2

            - name: linux
              run:  echo "Hello,Running on linux"
    
    build_windows:
        runs-on: windows-latest
        steps:
            - name: Retrieve the latest code pushed
              uses: actions/checkout@v2

            - name: windows
              run:  print "Hello,Running on Windows"

