name: Demo Actions
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieve the latest version of the code
              uses: actions/checkout@v2
            
            - name: Print the Message
              uses: echo "Welcome to World of Sarvesh!!"
